changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Obsidian Plugin
      labels:
        - plugin
    - title: MCP
      labels:
        - mcp
    - title: Indexer CLI
      labels:
        - indexer
    - title: Core
      labels:
        - core
    - title: CI / Ops / Monorepo
      labels:
        - ops
        - monorepo
    - title: Docs
      labels:
        - docs
    - title: Other Changes
      labels:
        - "*"
