name: Documentation issue
description: Report missing/incorrect docs
title: "docs: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Please avoid adding component/scope to the title (no `docs(ops): ...`, no `mcp: ...`).
        Use the `Component` field below and labels instead.

  - type: dropdown
    id: component
    attributes:
      label: Component (optional)
      description: Which area is the doc about?
      options:
        - Indexer (packages/indexer)
        - MCP server (packages/mcp)
        - Obsidian plugin (packages/obsidian-plugin)
        - Core/shared (packages/core)
        - Docs
        - Not sure

  - type: textarea
    id: location
    attributes:
      label: Doc location
      description: Which doc needs updating?
      placeholder: "docs/ops/local-dev.md, README.md, ..."
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What’s wrong / missing?
      description: Describe the doc problem and what you expected to see
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested fix (optional)
      placeholder: "Proposed wording, command, or link"
